"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.
Modified for Maison d'Edition Project (MySQL, DRF, JWT, React support).
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv
from datetime import timedelta

# Charger les variables d'environnement depuis le fichier .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Ajout du dossier 'apps' au chemin système pour des imports propres
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Render / production : DATABASE_URL (PostgreSQL) fourni par Render
import dj_database_url

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
_SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fallback-key')
if not DEBUG and _SECRET_KEY == 'django-insecure-fallback-key':
    raise ValueError(
        "SECRET_KEY doit être défini en production. "
        "Ajoutez SECRET_KEY=votre_clé_secrète dans votre fichier .env"
    )
SECRET_KEY = _SECRET_KEY

ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]
# Note : le test runner Django ajoute lui-même 'testserver' pendant les tests.


# Application definition
_cloudinary_apps = []
try:
    import cloudinary_storage  # noqa: F401
    _cloudinary_apps = ['cloudinary_storage', 'cloudinary']
except ImportError:
    pass

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    *_cloudinary_apps,
    'django.contrib.staticfiles',
    
    # Bibliothèques tierces (Page 4 PDF)
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_filters',
    'drf_spectacular',
    
    # Nos applications (créées dans le dossier apps/)
    'apps.books',
    'apps.users',
    'apps.orders',
    'apps.manuscripts',
    'apps.newsletter',
    'apps.contact',
    'apps.wishlist',
    'apps.coupons',
    'apps.core',

    # EXTENSIONS
    'django_extensions',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # Doit être placé haut
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Static files en production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Si DATABASE_URL est défini (Render, PostgreSQL), l'utiliser ; sinon MySQL (dev local)
_db_url = os.getenv('DATABASE_URL')
if _db_url:
    DATABASES = {
        'default': dj_database_url.config(
            default=_db_url,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT'),
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr' # Français

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Dossiers sources pour collectstatic : notre static/.
# Les fichiers de l'admin Django sont déjà trouvés par AppDirectoriesFinder
# (les ajouter ici provoquait des centaines d'avertissements "Found another file").
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# Créer staticfiles au démarrage (évite le warning si collectstatic n'a rien copié, ex. Render)
os.makedirs(STATIC_ROOT, exist_ok=True)

# Configuration Média (Uploads images livres/auteurs)
# Cloudinary en production si CLOUDINARY_CLOUD_NAME défini et package installé
_cloud_name = os.getenv('CLOUDINARY_CLOUD_NAME', '').strip()
_use_cloudinary = False
if _cloud_name:
    try:
        import cloudinary
        cloudinary.config(
            cloud_name=_cloud_name,
            api_key=os.getenv('CLOUDINARY_API_KEY', ''),
            api_secret=os.getenv('CLOUDINARY_API_SECRET', ''),
        )
        CLOUDINARY_STORAGE = {
            'CLOUD_NAME': _cloud_name,
            'API_KEY': os.getenv('CLOUDINARY_API_KEY', ''),
            'API_SECRET': os.getenv('CLOUDINARY_API_SECRET', ''),
        }
        _use_cloudinary = True
    except ImportError:
        pass

# Dummy credentials pour que les anciennes migrations importent cloudinary_storage sans crash
if not _use_cloudinary:
    try:
        import cloudinary
        cloudinary.config(cloud_name='dummy', api_key='dummy', api_secret='dummy')
        CLOUDINARY_STORAGE = {'CLOUD_NAME': 'dummy', 'API_KEY': 'dummy', 'API_SECRET': 'dummy'}
    except ImportError:
        pass

# Static files : stockage Django standard (pas de post-process WhiteNoise pendant collectstatic)
# Le middleware WhiteNoise sert quand même les fichiers depuis STATIC_ROOT en production
_static_storage = 'django.contrib.staticfiles.storage.StaticFilesStorage'
if _use_cloudinary:
    STORAGES = {
        'default': {
            'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
        },
        'staticfiles': {
            'BACKEND': _static_storage,
        },
    }
else:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': _static_storage,
        },
    }
# Compatibilité avec les paquets qui lisent encore l'ancien réglage (ex. django-cloudinary-storage)
STATICFILES_STORAGE = STORAGES['staticfiles']['BACKEND']
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Cache (LocMem en dev ; Redis en prod si CACHE_URL défini)
_cache_url = os.getenv('CACHE_URL')
if _cache_url and _cache_url.startswith('redis://'):
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _cache_url,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'terrenoire-cache',
            'OPTIONS': {'MAX_ENTRIES': 500},
        }
    }
CACHE_DELIVERY_TTL = 600  # 10 min pour la config livraison
CACHE_BOOKS_TTL = 300     # 5 min pour les listes de livres

# Configuration Email (réinitialisation mot de passe, notifications, etc.)
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')
# Logo : frontend/public/images/ ou backend/assets/images/ (priorité au backend)
LOGO_PATH = BASE_DIR / 'assets' / 'images' / 'logo_terre_noire.png'
if not LOGO_PATH.exists():
    LOGO_PATH = BASE_DIR.parent / 'frontend' / 'public' / 'images' / 'logo_terre_noire.png'
LOGO_URL = os.getenv('LOGO_URL') or f"{os.getenv('FRONTEND_URL', 'http://localhost:5173')}/images/logo_terre_noire.png"
# Gmail exige que l'expéditeur = compte SMTP. Si non défini, on utilise EMAIL_HOST_USER.
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL') or os.getenv('EMAIL_HOST_USER') or 'noreply@terrenoireeditions.com'
ADMIN_EMAIL = os.getenv('ADMIN_EMAIL', 'terrenoireeditions@gmail.com')
# Adresse qui reçoit les réponses des clients : l'expéditeur (contact@terrenoireeditions.com)
# n'a pas de boîte de réception, les réponses sont donc dirigées ici (en-tête Reply-To).
EMAIL_REPLY_TO = os.getenv('EMAIL_REPLY_TO', 'terrenoireeditions@gmail.com').strip()

# Envoi des e-mails, par ordre de priorité :
# 1. API HTTP Brevo si BREVO_API_KEY est défini (recommandé : Render bloque le SMTP sur les offres gratuites)
# 2. SMTP si EMAIL_HOST et EMAIL_HOST_USER sont définis
# 3. Console en dev, aucun envoi en prod (un avertissement est journalisé au démarrage)
BREVO_API_KEY = os.getenv('BREVO_API_KEY', '').strip()
_email_host = os.getenv('EMAIL_HOST', '').strip()
_email_user = os.getenv('EMAIL_HOST_USER', '').strip()
if BREVO_API_KEY:
    EMAIL_BACKEND = 'apps.core.email_backends.BrevoAPIEmailBackend'
elif _email_host and _email_user:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = _email_host
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_HOST_USER = _email_user
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
    EMAIL_TIMEOUT = 10  # Timeout 10s pour ne pas bloquer si le port SMTP est inaccessible
else:
    # Fallback : console en dev, échec silencieux en prod
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.dummy.EmailBackend'
    if not DEBUG:
        import logging as _logging
        _logging.getLogger(__name__).warning(
            "Aucun envoi d'e-mail configuré (BREVO_API_KEY ou EMAIL_HOST/EMAIL_HOST_USER) : "
            "les e-mails automatiques ne partiront pas."
        )

# Envoi en arrière-plan pour ne pas ralentir les requêtes (désactivé pendant les tests)
EMAIL_ASYNC = os.getenv('EMAIL_ASYNC', 'True') == 'True' and 'test' not in sys.argv

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuration du modèle utilisateur personnalisé
AUTH_USER_MODEL = 'users.User'

# Configuration Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'apps.users.jwt_cookie_auth.JWTCookieAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon_burst': '10/minute',
        'anon_sustained': '30/hour',
        'login': '5/minute',
        'register': '3/hour',
        'password_reset': '3/hour',
        'contact': '5/hour',
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Documentation API OpenAPI / Swagger
SPECTACULAR_SETTINGS = {
    'TITLE': "API Terre Noire Éditions",
    'DESCRIPTION': "API REST pour la maison d'édition Terre Noire Éditions (livres, commandes, utilisateurs, etc.)",
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    # En production, la documentation de l'API (schéma, Swagger, ReDoc) n'est
    # visible que des administrateurs : elle cartographie tous les endpoints.
    'SERVE_PERMISSIONS': (
        ['rest_framework.permissions.AllowAny'] if DEBUG
        else ['rest_framework.permissions.IsAdminUser']
    ),
}

# Lien de réinitialisation du mot de passe : 24 h (comme annoncé dans l'e-mail ;
# la valeur par défaut de Django est de 3 jours)
PASSWORD_RESET_TIMEOUT = 60 * 60 * 24

# Configuration JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=12),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}
# Cookies HttpOnly pour JWT (noms des cookies)
JWT_ACCESS_COOKIE_NAME = 'access_token'
JWT_REFRESH_COOKIE_NAME = 'refresh_token'

# Configuration CORS
# En dev (DEBUG=True) : autorise localhost
# En production : utiliser CORS_ALLOWED_ORIGINS dans .env (ex: https://terrenoireeditions.com,https://www.terrenoireeditions.com)
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOW_CREDENTIALS = True  # Requis pour les cookies HttpOnly
CORS_ALLOWED_ORIGINS = [
    o.strip() for o in (os.getenv('CORS_ALLOWED_ORIGINS') or 'http://localhost:5173,http://127.0.0.1:5173').split(',')
    if o.strip()
]
# Le domaine du frontend (FRONTEND_URL) est toujours autorisé, avec et sans "www.",
# pour éviter qu'un oubli dans CORS_ALLOWED_ORIGINS ne bloque tout le site.
_frontend_origin = os.getenv('FRONTEND_URL', '').strip().rstrip('/')
if _frontend_origin.startswith('http'):
    _scheme, _host = _frontend_origin.split('://', 1)
    _host = _host.split('/', 1)[0]
    _bare = _host[4:] if _host.startswith('www.') else _host
    for _origin in (f'{_scheme}://{_bare}', f'{_scheme}://www.{_bare}'):
        if _origin not in CORS_ALLOWED_ORIGINS:
            CORS_ALLOWED_ORIGINS.append(_origin)
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in (os.getenv('CSRF_TRUSTED_ORIGINS') or os.getenv('CORS_ALLOWED_ORIGINS') or 'http://localhost:5173,http://127.0.0.1:5173').split(',')
    if o.strip()
]

# =============================================================================
# Logging — visibilite du flux de paiement en production
# Par defaut Django n'affiche que WARNING+ quand DEBUG=False.
# Le logger bamboo_pay doit etre visible au niveau INFO pour
# diagnostiquer les problemes de paiement en prod.
# =============================================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'bamboo_pay': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Nos applications (e-mails, commandes, manuscrits...) : visibles dans les logs Render
        'apps': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# =============================================================================
# Sécurité production (actif uniquement quand DEBUG=False)
# https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
# =============================================================================
if not DEBUG:
    # Reverse proxy (DigitalOcean App Platform / Render) termine TLS
    # au load balancer. Cette config indique a Django de considerer la
    # requete comme HTTPS quand le header X-Forwarded-Proto est present.
    # Sans cette ligne, SECURE_SSL_REDIRECT cause une boucle infinie.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # Redirection HTTP → HTTPS
    SECURE_SSL_REDIRECT = True

    # HSTS (HTTP Strict Transport Security) — force le navigateur à utiliser HTTPS
    SECURE_HSTS_SECONDS = 31536000  # 1 an
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Cookies uniquement en HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Protection contre le sniffing MIME
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # Protection contre le clickjacking (X-Frame-Options)
    X_FRAME_OPTIONS = 'DENY'

    # Référer complet pour les redirections (évite la fuite d'info dans Referer)
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'