# Generated by Django 5.2.18 on 2026-10-06 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Format international : +24174301639 (nécessaire pour commander)",
                max_length=20,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Format accepté : +24174301639 (international) ou 074301639 (local).",
                        regex="^(\\+[1-9]\\d{7,14}|0\\d{7,9})$",
                    )
                ],
                verbose_name="Numéro de téléphone",
            ),
        ),
    ]
