# Generated by Django 5.2.18 on 2026-10-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="selection_rotation_hours",
            field=models.PositiveIntegerField(
                default=24,
                help_text="La sélection d'accueil est tirée au hasard et renouvelée à cette fréquence (24 = chaque jour, 168 = chaque semaine, 0 = jamais).",
                verbose_name="Renouvellement de la sélection (heures)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="selection_source",
            field=models.CharField(
                choices=[
                    ("all", "Tous les livres disponibles"),
                    ("featured", "Uniquement les livres marqués « Sélection »"),
                ],
                default="all",
                help_text="Avec « livres marqués », la sélection ne varie que s'il y a plus de 6 livres marqués.",
                max_length=20,
                verbose_name="Livres éligibles à la sélection",
            ),
        ),
    ]
