# Generated by Django 5.2.18 on 2026-10-06 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_orderitem_format_purchased"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="last_checked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Dernière vérification du statut auprès de Bamboo Pay",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[
                    ("MOBICASH", "Moov Money"),
                    ("AIRTEL", "Airtel Money"),
                    ("CASH", "Espèces"),
                    ("VISA", "Carte Visa"),
                    ("BAMBOOPAY", "BambooPay (page de paiement)"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PaymentNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="orders.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Bamboo Pay",
                "verbose_name_plural": "Notifications Bamboo Pay",
                "ordering": ["-received_at"],
            },
        ),
    ]
